### ISSUE TITLE
Docker pulling ARM64 image for `ssoready-api` on x86_64 host

### ISSUE THREAD

**Issue by JohnCMoon** [ssoready/ssoready#84]
Hi, I'm trying to get started with self-hosting SSOReady and I'm running into an issue running the docker-compose example. The `ssoready-app` and `ssoready-auth` containers are starting up properly, but the `ssoready-api` container fails with:

```
exec /api: exec format error
```

Sure enough, if I copy the entrypoint binary out of the container and run `file` on it, it shows it's compiled for ARM64. Here's a full reproduction:

```
 % uname -m
x86_64

% docker pull docker.io/ssoready/ssoready-api:main
main: Pulling from ssoready/ssoready-api
Digest: sha256:794f4ec0ea4747398157cb3ae3b26c3bf27f049bf576a76a90f525538360fbe6
Status: Image is up to date for ssoready/ssoready-api:main
docker.io/ssoready/ssoready-api:main

% docker run --name ssoready-api -it docker.io/ssoready/ssoready-api:main
exec /api: exec format error

% docker cp ssoready-api:/api ./
Successfully copied 19.5MB to ./

% file ./api
./api: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=pPoIUn4tZpukHsVKMb3S/oeCP9PQ6h2bwv5zwTlzn/lQ1XhmpaFRkgVFap93Xr/uF2f-2LH8M93f_QF-rH9, stripped
```

I've tried a few different tags of `ssoready-api` and gotten the same result. This issue still occurs when I manually pass `--platform linux/amd64` to the `docker pull` or `docker run` commands.

Any idea what might be going wrong?

**Comment by ucarion** [comment]
Thank you for raising this. 

I'm 99% sure this is because you're running x86, and to this point most users, including our entire dev and production stack, is on ARM. Given the thoroughness of your debugging, I'm guessing this is where your mind is at as well (thank you so much for that!).

In #85 and #86 we've started building for x86 and arm. Can you try to pull from the same docker images as before, but this time with tag `sha-bf52be0`?

**Comment by JohnCMoon** [comment]
Thanks for the quick support! I'm still encountering the same issue with `sha-bf52be0` (still only on `ssoready-api`). I see on Docker Hub both platforms are available now, but the amd64 platform still contains an arm64 binary.

**Comment by JohnCMoon** [comment]
Maybe it's because you're passing `GOARCH=arm64` here? https://github.com/ssoready/ssoready/blob/main/cmd/api/Dockerfile#L13

I'm not a Go guy, so I'm not sure if that's overridden elsewhere...

**Comment by ucarion** [comment]
Yes, you're almost certainly spot-on! I'm going to have to inject GOARCH from Docker's injected TARGETPLATFORM (https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope).

Thanks for your patience here. Next PR might be a little less instantaneous to come through, because I'm going to set up an x86 VM rather than putting out artifacts that I can't test.

**Comment by JohnCMoon** [comment]
No worries, I appreciate the quick support on a Friday afternoon! No big rush on my end.

**Comment by ucarion** [comment]
My QEMU-fu may have failed me in local testing, but it seems that this issue should be resolved now? I see in the CI logs for our builds that the `linux/amd64` platform build has the right GOARCH:

```
#14 [linux/amd64 build 8/8] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w -s" -o api ./cmd/api
```

The tip build to test with is `sha-13bbbf6`.

**Comment by JohnCMoon** [comment]
Yep, `sha-13bbbf6` works for me! Thanks so much!

**Comment by ucarion** [comment]
Thanks again for the really thorough bug report (and for the help debugging)! 🎉
