### ISSUE TITLE
Configurable Microsoft login endpoints

### ISSUE THREAD

**Issue by JohnCMoon** [ssoready/ssoready#90]
Hi - SSOReady currently has [this hardcoded Microsoft login endpoint](https://github.com/ssoready/ssoready/blob/82c39898de1e15cb156727bad1e4b6d083f94949/app/src/pages/LoginPage.tsx#L151):
```go
  const microsoftRedirectUri = new URL(
    "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
  );
```

Some high-security environments have a [different endpoints](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide) such as `login.microsoftonline.us` and `login.microsoftonline.mil`.

Could SSOReady make the Microsoft endpoint (or at least the TLD) configurable?

**Comment by Ned-oleary** [comment]
Will look into it!

**Comment by ucarion** [comment]
@JohnCMoon Are you aware of any alternative Microsoft OAuth servers I could use than `login.microsoftonline.com`? It seems like `login.microsoftonline.us` is limited to GCC High / DoD, and it's not clear to me that I would be able to test with it.

Alternatively, I can do one of the following:

1. Just put up an optimistic PR that assumes the hostname of a Microsoft OAuth server is as interchangeable as I might hope. You can then try running the result yourself against an alternative hostname. I don't love putting up Docker images that I can't fully test, but in this case the risk is pretty limited. I can revert if the change fails or if I don't hear back.
2. We can work on this together offline. This would be pretty similar to option (1), but instead of me publishing Docker images that you pull down and test, you build them locally and test. If it works, I'll publish them.

Either option presumes that you have access to GCC High / DoD. But I'm guessing you wouldn't ask if you didn't. I defer to your judgement here.

**Comment by JohnCMoon** [comment]
I agree it's unlikely there's an open `.us` endpoint you could use outside of an enterprise that has access already.

I think of the options above, number 1 would make the most sense to me. Especially if it's just an optional environment variable like `MICROSOFT_OAUTH_LOGIN_ENDPOINT` or something like that.

If you like, I'd be happy to test the PR before merging. I'm fine to build the docker images myself.

**Comment by ucarion** [comment]
I've pushed up a temporary modified build of the `ssoready-app` image at `ulysse/ssoready-tmp:ssoready-90-app` on `hub.docker.io`. That image accepts a new env var: `APP_MICROSOFT_OAUTH_AUTHORIZE_URL`. Functionally, the default value for that new setting is `https://login.microsoftonline.com/common/oauth2/v2.0/authorize`. I think that's all we need here, everything else is configurable?

You'll need to create a new OAuth client in order to test this. If that test works for you, I'll put up and merge a PR to mainline that functionality.

**Comment by JohnCMoon** [comment]
Thanks Ulysse - I've been swamped the last few days but will hopefully get a chance to test this week.

**Comment by ucarion** [comment]
Sounds good! No rush.

**Comment by ucarion** [comment]
@JohnCMoon, you reckon you'll get the chance to try this out at some point?

Definitely no obligation / expectations here, obviously. Just curious.

**Comment by JohnCMoon** [comment]
Hi @ucarion, thanks for the patience! I'm finally getting around to testing this out (had a kid in the interim!). I tried running your image, but looks like it's an ARM64 image:
```
The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3)
```
I don't have access to an ARM64 dev platform... do you think you could provide an x86 image (or a branch I could build)?

**Comment by ucarion** [comment]
Sorry, my bad! I'm building these artifacts locally, and defaults are making everything happen on arm64 unless I remember to build for a different platform. Try `ucarion/ssoready-tmp:ssoready-90-app-bis` (note the username changes from `ulysse` to `ucarion` versus my last suggestion).

Also, the code change in question is up on this draft PR: https://github.com/ssoready/ssoready/pull/137

**Comment by JohnCMoon** [comment]
Thank you - it looks like that works properly when I use `https://login.microsoftonline.us/common/oauth2/v2.0/authorize`! It asks for permissions and redirects to the callback URI as expected.

**Comment by ucarion** [comment]
Excellent! I'm going to move forward with #137. Glad it's working for you.

**Comment by ucarion** [comment]
Oh and mazel tov, @JohnCMoon!
